### ISSUE TITLE
unreadable "add" button in calendar (gnome 3.30)

### ISSUE THREAD

**Issue by ghost** [vinceliuice/Toffee-gtk-theme#1]
The "add event" button is unreadable until you start writing something.
![schermata da 2018-11-04 12-35-38](https://user-images.githubusercontent.com/20545323/47963669-8688d800-e02f-11e8-801c-4edc3230d7a1.png)

**Comment by vinceliuice** [comment]
Fixed now, you can try again

**Comment by ghost** [comment]
Thanks! It works perfect now!
